### ISSUE TITLE
Grey out charts after today's date

### ISSUE THREAD

**Issue by redstreet** [beancount/fava#1094]
It would be less distracting to cut off the time axis at today's date. Currently, if "2020" is selected, for instance, the graph extends the line all the way to the end of 2020 in the Balance Sheet->Net Worth graph:

![image](https://user-images.githubusercontent.com/691755/80271954-42055800-867a-11ea-85ce-78c4e239402d.png)

**Comment by yagebu** [comment]
If think it's more consistent if the time filter sets the start and end date irrespective of the current date. If you want to cut off today, just set the time filter to `2020 - today`

**Comment by redstreet** [comment]
I agree that it's more consistent in its current form, but I wonder if it can be made more useful, intuitive, and user friendly.

I'm thinking it's rare that anyone wants to see to the chart go beyond today in most use cases. The filter would still allow for that when explicitly set; but would cut off to today where it makes sense. What's intuitive?

Easier cases:
2020: 2020-01-01 - today
2018 - 2020: 2018-01-01 - today
2018 - 2020-08-31: 2018-01-01 - 2020-08-31

Trickier cases. These are uncommon, so they matter less IMO:
2019 - 2021: 2019-01-01 - 2021-12-31
2021 - 2024: 2021-01-01 - 2024-12-31

Anyway, that's my two cents. 'today' helps, thanks for the pointer. Please feel free to close this if you think it doesn't provide much value.

**Comment by redstreet** [comment]
BTW, `today` doesn't seem to work in 1.14. Is it newer? I don't see it in the help either.

**Comment by yagebu** [comment]
> I agree that it's more consistent in its current form, but I wonder if it can be made more useful, intuitive, and user friendly.

I personally prefer the current behaviour and find it more intuitive that any special casing based on the current date. Of course the chart points beyond the current date don't provide much value, but I find the chart more useful due to their more symmetric structure. In your `2018-2020`, I'd want all the three years to be of the same width...

> BTW, today doesn't seem to work in 1.14. Is it newer? I don't see it in the help either.

Sorry, it's `day`, so `year - day` for the current year for example. It's all documented in the help pages (filters).

**Comment by jpluscplusm** [comment]
Sorry to add-to/re-open a closed discussion, but I had a very small insight into this issue, and a compromise suggestion.

I've been (very slightly!) bitten by this. Typing 2020 into the time selector is the easiest way to say "my recent history", and it took me a good 30 seconds of being surprised at why I was seeing "data" across the /entire/ year, before I realised that the last-set value/balance/etc persists into the future. 

How about this as an idea:

Instead of cutting the graph off at "today" (which I agree is a bit draconian), how about greying/desaturating/increasing-the-alpha on the plotted time series which are both beyond today, and don't have data recorded in the future?

To my mind that'd make everyone happy:

- simpletons like me will get an immediate warning that we're not seeing "real" data, but a plotting artefact
- folks who like the current un-curtailed view will continue to see a line plotted into the future, albeit more lightly coloured/etc
- folks with transactions in the future won't be affected at all
- the principal of least surprise isn't violated for anyone :-)

Thoughts?

HTH!
J

**Comment by yagebu** [comment]
> Instead of cutting the graph off at "today" (which I agree is a bit draconian), how about greying/desaturating/increasing-the-alpha on the plotted time series which are both beyond today, and don't have data recorded in the future?

I like it! Although I'd always grey/desaturate irrespective of whether there are any transactions in the future. This keeps the implementation simpler and the behaviour more consistent. I also assume that people with transactions in the future don't live in the future so the distinction past/future could also be useful for them :D

**Comment by redstreet** [comment]
Nice idea, @jpluscplusm, +1.

**Comment by yagebu** [comment]
Implemented in #1282
