### ISSUE TITLE
Cannot type date into "Time" on Safari

### ISSUE THREAD

**Issue by waynema02** [beancount/fava#1098]
# Summary

When trying to type custom date range like "2017-01" into the "Time" input filter in the upper right corner, the main content does no update accordingly. However, directly changing URL with parameter "time=2017-01" updates the content.

Besides, this bug only happens on Safari, but not on Chrome or Firefox.

# Steps to reproduce on Safari:
0. Open Safari
1. Go to [demo page](https://fava.pythonanywhere.com/example-with-budgets/income_statement/)
2. Type "2017-01" in the "Time" input box
3. Press Enter.

# Current Behavior:

The content does **not** change, looks like the date filter "2017-01" is not propagate correctly.

![image](https://user-images.githubusercontent.com/1069722/81451357-2cdbff00-9139-11ea-9191-94592cc07b15.png)

# Expected Behavior:

The content change to show only time for Jan, 2017:
![image](https://user-images.githubusercontent.com/1069722/81451282-fc946080-9138-11ea-80c0-23814fdaed1d.png)

# Versions
* Safari version: `Version 13.1 (15609.1.20.111.8)`
* OS: `10.15.4 (19E287)`

**Comment by yagebu** [comment]
Thanks for the bug report. From an initial glance, the spec seems to be pretty clear on how an Enter key press should be interpreted in form. Unless this is due to some other frontend bug that we only run into on Safari, it might be a bug in Safari.

I don't have a Mac so I can't really debug this. Could you try debugging this a bit? (Opening the developer console and looking for errors there would be a start).

**Comment by yagebu** [comment]
Still can't reproduce this for obvious reasons - but I'll address it by also triggering the submit on the `blur` event, that is, when focus leaves the input. That should ensure that inputs and filters are always in sync.
