### ISSUE TITLE
Adopt pipenv/poetry to make build reproducible

### ISSUE THREAD

**Issue by yegle** [beancount/fava#1138]
Similar to https://github.com/beancount/beancount/issues/542

**Comment by yagebu** [comment]
I don't think we'd really gain anything from using pipenv or poetry. Most of the build happens in node, where these tools wouldn't help at all. In Python, we don't do anything during build (other than generating the version number with `setuptools_scm`), so I don't think it would turn any more reproducible with these tools.

In contrast, not having a fixed development environment improves Fava as it will more easily surface bugs due to some incompatibilities.
