### ISSUE TITLE
Follow WAI ARIA practices for modals

### ISSUE THREAD

**Issue by danuker** [beancount/fava#1191]
First of all, thank you for the amazing software! I love it! Still, I found a bug that annoys me.

When I add a new transaction using the dialog (such as with the `n` key), or when I click "Save and add new", the first field is not focused. Tab just cycles through fields behind the new transaction dialog.

This used to be focused in v1.10. Now I have to manually click in the date field. I would love for this behavior to be restored.

In addition (let me know if this should be a separate bug), the date resets to today, not the last thing I added.

**Comment by danuker** [comment]
In addition, when I add a new posting by keyboard, its first field is not focused.

**Comment by yagebu** [comment]
I removed this focusing of inputs in b7440f2224ad03eef7d3a3eb1673a250c1b26539, probably due to some minor bugs with the implementation. I think the bigger issue here, which you also mention, is that we do not trap focus and generally do not follow the [WAI ARIA practices for dialogs](https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal).

> In addition (let me know if this should be a separate bug), the date resets to today, not the last thing I added.

That was an intentional change as I personally found that to be more practical.
