### ISSUE TITLE
The "Converted to" List filter cannot distinguish currency and commodity

### ISSUE THREAD

**Issue by anels** [beancount/fava#1226]
![image](https://user-images.githubusercontent.com/1177049/105902411-77592080-5fd3-11eb-9124-132a4c3c64ad.png)
When a symbol of a commodity (ticker) is the same as a currency symbol (e.g. 'AMD') it will be displayed on the "Converted to" list which is annoying.

In [the discussion on this issue](https://github.com/beancount/fava/issues/1041#issuecomment-581032924), it seems the filter is based on https://www.currency-iso.org/en/home/tables/table-a1.html. I think maybe fava should add an option to allow users to specify the *Currencies* to make it easier to manage.

**Comment by yagebu** [comment]
I'm not too keen to add an option for this.

**Comment by jeffwheeler** [comment]
I want to add that I was also very confused by this. I hold a variety of equities that happen to share names with currencies. I didn't realize that's why they were listed until I saw this bug report, thanks!

<img width="185" alt="Screen Shot 2021-05-11 at 8 58 16 PM" src="https://user-images.githubusercontent.com/14618/117916547-38a65800-b29c-11eb-89e5-26c824f9190f.png">

**Comment by yagebu** [comment]
Well, I guess due to US ticker symbols commonly clashing with ISO currency names, that we should add an option to specify the list of conversion currencies. A PR would be welcome.

**Comment by yagebu** [comment]
This option has been implemented in #1439
