### ISSUE TITLE
'Stacked' Charts

### ISSUE THREAD

**Issue by aclindsa** [beancount/fava#1251]
There are several cases where it would handy to be able to use 'stacked' bar and/or line charts in fava. Examples include:

- Studying how expenses change over time (trying to pinpoint where a rise in expenses came from currently requires flipping back and forth between the top-level expenses chart and charts for expense sub-accounts)
- Visualizing market value of investment portfolios relative to cost basis over time

@yagebu I have two questions for you:
1. If I spent the time to implement such a feature, would you be willing to accept it?
2. If so, do you have any guidelines or initial instructions to point me in the direction of how you would want it to be implemented? (Obviously small stuff can be fixed with code reviews, but I'd rather not design it in a way you strongly dislike to begin with)

**Comment by mattr555** [comment]
[This is another cool example](https://imgur.com/a/0eDD9KE) of a stacked chart that I've been wanting to replicate in Fava.

**Comment by yagebu** [comment]
I'll close this issue since we already have an open issue for stacked charts: #716.

@aclindsa: 

>  1. If I spent the time to implement such a feature, would you be willing to accept it?

Yes, this would be very welcome :)

> 2. If so, do you have any guidelines or initial instructions to point me in the direction of how you would want it to be implemented? (Obviously small stuff can be fixed with code reviews, but I'd rather not design it in a way you strongly dislike to begin with)

I don't have any strong thoughts on this yet. I guess this could be implemented quite similarly to the existing charts, trying to have the new data structures that are generated by Fava align with the existing ones (in some sense the data required is a combination of the existings hierarchical account charts and the time series charts). If possible, I think it would also be good if these new charts are not entirely new charts (in terms of the code generating the charts) but we add this as an additional feature to the existing code.
