### ISSUE TITLE
Sorting querytable not sorting by value but by string representation

### ISSUE THREAD

**Issue by LucaBernstein** [beancount/fava#1256]
Hi all!

- Noticed first in `holdings/by_currency/` (How to reproduce):
- (version `fava, version 1.19.dev83+g3ecb83a7.d20210420`)
- Click on `market_value` table header
- Then table will be sorted, though not by value but by string representation (see following example)

|...|market_value `(sorted by, ASC)`|
|---|---|
|...|100.00 EUR|
|...|12.00 EUR|
|...|2.10 EUR|
|...|2.90 EUR|
|...|3000.00 EUR|

Had a brief look in the code already: bean-query is fine: With `ORDER BY market_value DESC` in the query the values in the resulting table are sorted just fine.

So I guess querytable sorting does not work properly, because the value in the table is of type string due to the `EUR` appendix instead of int.

So the question is, how can we make the values in the table sort correctly?

- Either we could add / change the `ORDER BY` clause in the query on click on the table header (difficult integration?)
- Or we look into the use of querytable and see how this can be done
  - Encountered in `src/fava/templates/holdings.html`
  - `src/fava/templates/_query_table.html` could be a great spot to look at next

I would be happy if you would have any more remarks and ideas to this. Looking forward to working on a solution with you as I really like fava.

Thanks in advance and kind regards,

Luca

**Update**:

- Table sorting is made possible by `<table is="sortable-table" class="queryresults">`
- `sortable-table` is defined in `frontend/src/main.ts` to use class `SortableTable`
- call to `sortElements` in `frontend/src/sort.ts` which applies sorting by `getValue` function result
- We should have `data-sort` attribute `num` on table header -> `numComparator`should be used. Does parsing not work?

**Comment by LucaBernstein** [comment]
Root cause is that `data-sort` attribute of `*_value` fields is `string` instead of `num`.

If that would be solved, it would work out of the box.

I will add a PR.

**Comment by yagebu** [comment]
The problem here is that the value in the `market_value` column is an inventory, so it can contain multiple positions. There's no good or "right" way to sort arbitrary inventories (is `10 USD, 9 EUR` less than or greater to `9 USD, 10 EUR`?). In this case here, you end up with inventories that only contain a single position, so they can easily be sorted but we can't really add sorting for this column in a meaningful way in general.

Even for single positions, we currently can't really sort them in the frontend, since for that we would have to parse them as we would otherwise mix up positions of different currencies. If we move to frontend-rendered query tables at some point that could be changed (we could then even decide whether a column containing inventories is sortable depending on the data).

Since the `order by` clause works in your case, I'd suggest you add that to the query and save it as a custom query in your Beancount file.
