### ISSUE TITLE
Change default port (at least on macOS)

### ISSUE THREAD

**Issue by caesar** [beancount/fava#1373]
macOS now uses port 5000 by default for AirPlay discovery (https://news.ycombinator.com/item?id=29006861).
Attempting to start Fava with the default port now fails silently on macOS (it says it's running, but the web interface doesn't load because the port is already in use by the system).

Port 5000 is in any case already a reserved port for UPnP:
- https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=88
- https://www.grc.com/port_5000.htm

It would be better to use a port in the 8000+ range (and also to detect if the port is already in use and fall back to a higher port).

**Comment by yagebu** [comment]
Thanks for the report :) 

This port was chosen simply by being the default port that the Flask dev server binds on. I think I'll stick with that default like Flask (https://github.com/pallets/flask/issues/4328), but Fava should definitely error out if the port is already in use. It seems that it currently doesn't due to cheroot binding to ip6 localhost (so [::1]:5000) if ip4 localhost is in use (which I find to be surprising behaviour). I'll fix that.

**Comment by chrisirhc** [comment]
Encountered this issue today. Seems like the error handling in #1378 may not be working.

**Comment by yagebu** [comment]
A PR with a fix would be welcome then :)

**Comment by jbrok** [comment]
You can just add an alias in the `~/.zshrc` file to set the port to a different one. I don't have issues with it on MacOS.

```
alias startfava="fava main.beancount -p 5001"
```

You can then just type `startfava` in your Terminal. Edit the port and file to your needs

**Comment by slashformotion** [comment]
I used python default web server to bind the loopback ipv4 and ipv6 on port 5000:
```
➜ python3 -m http.server 5000
Serving HTTP on 0.0.0.0 port 5000 (http://0.0.0.0:5000/) ...
``` 
(and in another terminal)
```
➜ python3 -m http.server -b ::1 5000
Serving HTTP on ::1 port 5000 (http://[::1]:5000/) ...
```

let's see what tcp port is open:
```
➜ ss -tln
State                  Recv-Q                 Send-Q                                 Local Address:Port                                 Peer Address:Port
LISTEN                 0                      5                                          127.0.0.1:5000                                      0.0.0.0:*
LISTEN                 0                      511                                        127.0.0.1:6463                                      0.0.0.0:*
LISTEN                 0                      5                                              [::1]:5000                                         [::]:*
```
We can see that both ipv4 and ipv6 address are in use for port 5000

then I started fava 

``` 
➜ uv run src/fava/cli.py  tests/data/query-example.beancount
Starting Fava on http://127.0.0.1:5000
Error: Cannot start Fava because port 5000 is already in use.
Please choose a different port with the '-p' option.
```

*The error is expected because both ipv4 and ipv6 address are in use for port 5000.*

Then I closed all my terminal sessions.

I started only the ipv4 python server this time:
```
➜ python3 -m http.server -b 127.0.0.1 5000
Serving HTTP on 127.0.0.1 port 5000 (http://127.0.0.1:5000/) ...
```

let's the listening ports:
```
➜ ss -tln
State                  Recv-Q                 Send-Q                                 Local Address:Port                                 Peer Address:Port
LISTEN                 0                      5                                          127.0.0.1:5000                                      0.0.0.0:*
LISTEN                 0                      511                                        127.0.0.1:6463                                      0.0.0.0:*
```
only the ipv4 one as expected

and when we run fava:
```
➜ uv run src/fava/cli.py  tests/data/query-example.beancount
Starting Fava on http://127.0.0.1:5000
Error: Cannot start Fava because port 5000 is already in use.
Please choose a different port with the '-p' option.
```
*I get the expected error.*

I am testing this on a linux machine so on Macos the result might be different. But I would be very surprised that it is the case...

Unless someone can successfully reproduce this on a Mac I think this can be closed.
