### ISSUE TITLE
Don't suggest closed accounts when adding a transaction

### ISSUE THREAD

**Issue by fdw** [beancount/fava#1377]
When I add a transaction, I'm still suggested similarly-named accounts that have been closed for quite a while. As this results in an invalid transaction anyway, maybe it would be nicer to not suggest these accounts at all.

Fava version: `1.20.2.dev0+gb49d0540.d20211019`

**Comment by yagebu** [comment]
This has come up before in #492. Since the frontend part is more advanced nowadays, this might be more feasible to implement nowadays. A PR would be welcome :) Note that we can't just filter out closed accounts but we rather need to filter out accounts that were closed before the date of entry that is currently being added.

**Comment by fdw** [comment]
Ah, sorry, I had searched but didn't find that issue :(

Do you have a pointer where/how this might be implemented?

**Comment by yagebu** [comment]
No problem :)

We basically need a mapping of account names to close dates in the frontend. From the Python side we could supply this in `fava.core.attributes` via `_layout.html` to the frontend, which would be loaded in `frontend/src/stores/index.ts`. This mapping could then be used in the `Transaction.svelte` component to filter the account suggestions.
