### ISSUE TITLE
First load is very slow

### ISSUE THREAD

**Issue by aronsky** [beancount/fava#1417]
Hi,

I'm running fava in a custom docker container. I have an automation that pulls information from CC/banks several times a day, and imports changes into the beancount files.

I noticed that many times, when opening fava, the first load time is very long, but working with it afterwards is a breeze. It bothered me for a while, but not enough to do something about it.

Recently, I decided to investigate further. The delay appears to happen on first page load after launching the docker, as well as after making changes to the beancount files with my cronjob, which uses beancount API (I suppose that invalidates the cache; editing beancount data from Fava or changing the files directly on disk is very quick and doesn't result in any slowdowns).

I ran fava with profiling enabled, and saw that serving the first request for `GET /` (well, actually the redirect to the ledger that follows) took almost 10 seconds. Requesting the same page afterwards (or any page, really) was really fast afterwards - between several milliseconds and half a second for some heavy pages.

I then decided to add a simple `HEALTHCHECK` line to my `Dockerfile`, which looks like this:

`HEALTHCHECK CMD wget --spider http://localhost:5000/ || exit 1`

Lo and behold, no more slow loading - every time I open fava in my browser now, it loads instantly.

I'm not sure what processing is delayed until actual requests start coming in, but I think there should be an option at least to perform it immediately and not lazily.

**Comment by yagebu** [comment]
Not loading the files on first load is intentional (it used to be necessary in the past which made the WSGI app harder to use). And for instances of Fava that are immediately accessed, it doesn't make any difference. For instances of Fava that are not immediately accessed, it avoids a wasted computation if the file is changed until first use.

> but I think there should be an option at least to perform it immediately and not lazily.

Since you describe cronjob-based changes to your file would actually just waste CPU cycles for the inital load and I don't see how that would help in your case. Sending a request to Fava like you did seems like the right solution here or how would you expect Fava to address this?

**Comment by aronsky** [comment]
OK, I understand the reasoning, and given that a workaround exists, it seems no changes are necessary.
