### ISSUE TITLE
Race condition in filters corrupts ledger.end_date value

### ISSUE THREAD

**Issue by PhracturedBlue** [beancount/fava#1418]
I have an extension that makes use of `ledger.end_date`
However the end_date gets corrupted (specifically, the `value` gets set to `None`) every time the `changed` endpoint is called.  Since the application is threaded, this means that the end_date is corrupted during the extension processing.  I'm not sure what a proper fix for this would look like, since multiple requests from different browsers could change the end_date parameter at any time, so I think the current implementation is fundamentally unsafe, and filters should be preserved in thread-local variables.

However, with a single browser connection, this can be made to behave sanely via:
```
--- a/src/fava/application.py
+++ b/src/fava/application.py
@@ -209,11 +209,15 @@ def template_context() -> dict[str, FavaLedger]:

 @app.before_request
 def _perform_global_filters() -> None:
+    if request.endpoint in ('json_api.get_changed', 'json_api.get_errors'):
+        return
     ledger = getattr(g, "ledger", None)
     if ledger:
         # check (and possibly reload) source file
         if request.blueprint != "json_api":
             ledger.changed()
```

**Comment by yagebu** [comment]
Hey, thanks for the report. I was somewhat aware of the danger of mutating the ledger here but in the early single-threaded days it wasn't a problem and then I was too lazy to do anything about it. The complete fix for this that I am working on is to generate a new object (the filtered ledger) in each report (with some caching) instead of mutating the ledger itself.

I've also added your patch in #1429 in the meantime.
