### ISSUE TITLE
Feature request: different colors for positive and negative bars

### ISSUE THREAD

**Issue by AlphaJack** [beancount/fava#1517]
What do you think about implementing an option to fill single-bar charts with two colors based on their value?  
In this case, I have manually filled in green the bars above 0, and in red the negative ones:

![fava2colors](https://user-images.githubusercontent.com/19962243/208076626-db703c12-b643-498e-bf58-3f0a8fa8e673.png)

By default they are all blue:

```svg
<rect fill="rgb(126, 174, 253)" width="29.51824817518248" x="0" y="135.8056037554339" height="61.58523968170877"></rect>
```

The coloring method is related to #843

**Comment by yagebu** [comment]
I'm not too keen to add a third bar coloring logic:

1. stacked bars : colors distinguish between accounts
1. single bar - colors distinguish between currencies
1. (suggested) single bar, single currencies - distinguish between negative and positive

In particular since it would only apply to the non-default single bar mode in the special case of a single currency. Also, I think the green/red split which I'd connect with good/bad is problematic due to e.g. Income generally being negative - so my net income would be red if my net worth grows (which I'd consider good :D)

Maybe we can add a somewhat pronounced line a 0? or use some other sort of visual hint to more clearly distinguish positive and negative? suggestions welcome.

**Comment by AlphaJack** [comment]
I see the issue with multiple currencies, maybe a thicker line at 0 could be a great solution for all the available modes
