### ISSUE TITLE
Large increase in browser memory use from 1.21 to 1.22

### ISSUE THREAD

**Issue by falsifian** [beancount/fava#1539]
With fava 1.22 or later (I've tried 1.22, 1.22.3, 1.23.1), fava seems to use a lot more browser memory than before.

I discovered this because Firefox tabs started crashing until I increased their memory limit with `ulimit -d`.

I haven't found a great way to measure the use (Firefox's `about:memory` doesn't seem to work well on OpenBSD), but I got a rough estimate by looking at the `SIZE` column in top:

- fava 1.21: None of my Firefox processes have SIZE > 600M. (Probably the process corresponding to fava is using somewhat less.)
- fava 1.22+: I'm seeing SIZE numbers ranging from 4242M to 4806M.

So that's an increase of at least 7x, probably more.

My ledger is fairly large: 27442 lines in my beancount files combined, and I have plugins that might increase the total number of postings somewhat. (For my own reference: I'm at commit `c9ac3c6d` of my ledger.)

Let me know if it would help for me to try to make a simplest reproducible example (maybe 10000 identical transactions or something) or to try to supply some kind of anonymized version of my ledger.

**Comment by yagebu** [comment]
Hey, thanks for the report.

I've not been able to reproduce this issue (Firefox 109 on Linux, Fava latest main) with my personal ledger, which is of a similar size. I've switched between various reports and tracked the overall memory usage with `about:processes` and also took some memory snapshots with the dev tools. There were some temporary increases but after GC it all seemed to level out again.

Can you try installing Fava from `main` (https://beancount.github.io/fava/development.html) and seeing if you can still reproduce this? Which reports or specific interactions with Fava drive memory usage up?

**Comment by falsifian** [comment]
Will hopefully have time to try `main` next weekend, and maybe even send an example ledger that reproduces it. In the meantime, some information in case it helps:

The page I have trouble with is the default page, the income statement at `http://localhost:5000/beancount/income_statement/`". I just dried going directly to the following URLs, chosen somewhat arbitrarily, and they loaded without trouble:
* `localhost:5000/beancount/journal/`
* `http://localhost:5000/beancount/balance_sheet/`
* `http://localhost:5000/beancount/errors/`

I noticed the bar chart on my income statement page goes back to 1900 (probably some weird transaction in my ledger) but that wasn't enough to reproduce it with a different ledger.

**Comment by falsifian** [comment]
The problem still happens at main (commit 8066b202cc6febb47005eb338c0d5fe2b85d744e). Also, I found a simple example ledger that reproduces it: use the following script to generate a beancount file.

```
print("""option "operating_currency" "CAD"
1900-01-01 open Assets:Cash
""")

for month in range(1, 13):
  for day in range(1, 29):
    print(f"1900-01-01 open Expenses:Groceries-{month}-{day}")

for year in range(1900, 2000):
  for month in range(1, 13):
    for day in range(1, 29):
      print(f'{year}-{month:02d}-{day:02d} * "groceries"')
      if True:
        sign0 = ""
        sign1 = "-"
      else:
        sign0 = "-"
        sign1 = ""
      print(f"  Assets:Cash  {sign0}10.00 CAD")
      print(f"  Expenses:Groceries-{month}-{day}  {sign1}10.00 CAD")
```

(33264 transactions with 336 accounts.)

The problem happens when I simply navigate to `http://localhost:5000` and get redirected to the income statement.

fava version 1.21 has no trouble: I can run Firefox with my default data ulimit of 1572864 KiB. At commit 8066b202cc6febb47005eb338c0d5fe2b85d744e, Firefox crashes with that ulimit, and if I increase the ulimit, I see memory use > 3GiB.

**Comment by bnabholz** [comment]
The fast workaround I found was to change the chart mode back to "Single Bars."

I spent some time with `git bisect` and the change was inadvertently caused by commit 2fcd605, which fixed a bug that prevented "Stacked Bars" from working on the income statement.  That commit was between v1.21 and v1.22.  The root cause however is the low performance of Stacked Bars when dealing with a large time range or a large number of accounts (or both).

I was able to improve the performance of Stack Bars by changing [BarChart.svelte line 141](https://github.com/beancount/fava/blob/main/frontend/src/charts/BarChart.svelte#L141) from:

`{#each stack.filter((b) => !Number.isNaN(b[1]) as bar}`

to:

`{#each stack.filter((b) => !Number.isNaN(b[1]) && b[0] !== b[1]) as bar}`

The extra conditional excludes accounts whose balances didn't change during the month.  This reduces the number of DOM elements by skipping the ones that would be zero height, assuming that there are many accounts without transactions each month.

Before the change, the sample ledger from @falsifian used between 3.6GB and 4GB of memory.  After the change it is using between 640MB and 700MB.  It is still a little slow, but that ledger is pretty demanding.  For typical usage it might be good enough.  **I can submit a PR with the change if needed.**

A longer term fix with a large number of accounts might be:

- group the affected accounts for each time interval by positive or negative change
- choose only the largest X (5-10?) accounts in each group for display
- sum the remaining accounts and list them as  "other"

I can work on implementing that but I'm just starting to get familiar with the codebase so I have a lot to learn.

**Comment by yagebu** [comment]
Thanks for debugging this @bnabholz! 

I've made the following changes in #1579:

- The filter adjustment as suggested by you
- Reducing the maximum number of intervals in the bar charts to the last 100 - having more doesn't really add any value since the bars will not really be visible.
- Moving up some event handlers

With those changes, memory usage for the stacked bar charts seem to be pretty acceptable to me.

**Comment by falsifian** [comment]
Thanks @bnabholz and @yagebu! That fixed the memory problem for me.

**Comment by JacksonVasconcelos** [comment]
Changed my own maximum value to 240 instead of 100. Just 100 limits monthly view to 2015-2016. My file goes to 2012. Still avoids a 1900 memory error. Hard to notice the diference in mobile, but noticible on desktop.
