### ISSUE TITLE
sign for credit/debit configurable

### ISSUE THREAD

**Issue by MJochim** [beancount/fava#1612]
Fava version 1.24.4

I wonder if it should be configurable whether asset and expense accounts have a plus sign and the other account types a minus sign; or vice versa. I use a different convention than the Beancount docs and while this is mostly no problem, some graphs in Fava fail with my books.

Background: Different types of accounts are associated with either a positive sign or a negative sign in Beancount. Traditional accounting uses the terms credit and debit instead. At the end of the day, both approaches have the same result; therefore they can be and are mapped onto each other. See Beancount docs [0] for more details. However, it is very much arbitrary whether you map positive sign to credit and negative sign to debit or vice versa. See [1], which is also part of the Beancount docs. Beancount opts for this mapping: [2].

My problem is, I learned Beancount and accounting at the same time and back then, I didn’t realize that Beancount even had a convention for mapping. To me, the other mapping came more natural and still feels more natural (of course I am heavily biased by now due to how my own books are structured). I have used the other mapping ever since and it is absolutely no problem as far as Beancount is concerned. I just get the other type of sign in everything I do. In Fava, however, four graphs remain empty (saying “chart is empty“) because they don't work well with account values below zero (specifically: the income and expenses graphs in the income statement tab; and the liabilities and equity graphs in the balance sheet tab).

I realize this problem is because I am violating Beancount convention, but I didn’t realize this when I made that choice.

I sometimes use this patch to make the graphs work for my books:

```
--- a/fava/core/__init__.py	2023-05-16 10:40:08.753643687 +0200
+++ b/fava/core/__init__.py	2023-05-16 10:40:21.506292331 +0200
@@ -408,7 +408,7 @@
             The sign of the given account, +1 for an assets or expenses
             account, -1 otherwise.
         """
-        return get_account_sign(account_name, self.account_types)
+        return -1 * get_account_sign(account_name, self.account_types)
 
     def interval_balances(
         self,

```

I have not encountered problematic side effects of this patch.

Does anyone else have this issue? Would you consider a pull request in this vein if it were properly done, for example with a new `fava-option`?

[0] https://beancount.github.io/docs/the_double_entry_counting_method.html#credits-debits
[1] https://groups.google.com/g/beancount/c/S_Ac6sbetWg/m/Ec-QeB8CBAAJ
[2] https://beancount.github.io/docs/beancount_cheat_sheet.html

**Comment by yagebu** [comment]
I wouldn't want to add an option for this sort of behaviour change, but I think we can get rid of this logic with the +1 or -1 here altogether. Even when sticking to the Beancount convention one might have negative expenses in a certain time frame for example.

This +1 or -1 is needed for the hierarchy type charts (so sunburst/treemap) because those do not support having both negative and positive values in the tree, so we have to pick whether to show only all the positive values or all the negative values. Instead of determining this from the account name, we could just use the following heuristic: If your root account balance is negative (in a currency), for the hierarchy in that currency we just show all the negative values and vice versa for positive values.

**Comment by MJochim** [comment]
Works great in 1.26 :heart:. Thanks a lot!
