### ISSUE TITLE
Clearing Transaction Insert Form

### ISSUE THREAD

**Issue by yogiparish** [beancount/fava#1674]
Ive noticed a change in behavior since updating (unfortunately, it's been a while so I can't remember when). Now, when using the '+' form to add a new transaction, fava populates the fields with the last transaction. This is in 90% not the behavior I want.

How can I make it clear all fields? (is there a shortcut to do this, or an option?)

Thanks for any help.

**Comment by xuhcc** [comment]
The form also doesn't disappear after submission.

I think this bug was introduced in 1.26. The form is still broken in 1.26.1

**Comment by fdw** [comment]
I find this bug very annoying, so I dug through the code. It seems to me that the problem was introduced with [`b46b068b`](https://github.com/beancount/fava/commit/b46b068bb3d538417b3095d95e84a19c4c9c418b#diff-c7df859026337d877a3bea226ec6064ad4d5728e7592243deae03cef943ad630L26):
```
entry = entry.constructor(added_entry_date);
```

In Firefox at least, that throws a `class constructors must be invoked with 'new'`, preventing `entry` from being overwritten with an empty one and the overlay to be closed.

Previously, there was some more elaborate logic to call `new constructors[type](date)`. I'm not sure what the desired solution is, but I'd be willing to fix it, if you give me a hint 🙂

**Comment by yagebu** [comment]
Thanks @fdw for investigating and finding the cause! Somewhat embarassing that this bug made it through (but also annoying that Typescript didn't catch it). Adding the "new " should fix it.
