### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by yogiparish** [beancount/fava#1675]
Hi, 

I am running fava on macOs 13.1 and installed the latest version in a pipenv environment. 
I've noticed that the balance sheets don't immediately refresh after I've entered or change a transaction. This used to be the case before. If I manually refresh, the transactions are all there.  Sometimes the balance sheets does update, but then it only shows the update before last, not the latest entered transaction.

- I've moved the beancount file to different places in the filesystem, ie local and remote, but no change in behavior.
- I've changed autoload to yes but no change in behavior.
Any help would be appreciated.

thanks

**Comment by lyon-fnal** [comment]
I have the same problem.

**Comment by mortisj** [comment]
Same issue here, using Firefox on Linux if that is relevant.  I can see that refreshing after every update might be a performance problem for people with large files, so I'd suggest that there be an option for this.

**Comment by yagebu** [comment]
I'm not able to reproduce this. For example on the balance sheet I get the following (expected behaviour) a few seconds after making a change (that affects the balance of a shown account):

- with auto-reload: False: the reload button is shown. On pressing `r` the report reloads and seems to update correctly
- with auto-reload: True: the page automatically reloads and updates the balance.

Could someone provide some steps (ideally with one of the example files) to reproduce this? Also, could you check Fava and browser log messages for any errors?

**Comment by mortisj** [comment]
Hi Yagebu:

First of all, thanks for all you do.  Fava is awesome.

Here are the steps that I am following:

1. Select an expense account to bring up the corresponding account journal page
2. Press the "+" in the left pane to add a transaction
3. Enter transaction details, uncheck continue, press Save

A green bar pops up for a few moments saying "Stored 1 entries".  Apart from that the journal display does not change.  Fava's yellow reload button does not appear.

Press the browser's reload button, journal display updates to show the newly added transaction.

No errors in the browser console.  I don't where to look for a Fava log.

I've tried it with and without auto-reload, same result.

Beancount 2.3.6, Fava 1.27.1.

Thanks.
