### ISSUE TITLE
Opening fava with multiple *.beancount-files not working since 1.27

### ISSUE THREAD

**Issue by gismo141** [beancount/fava#1734]
I‘m using fava on docker with multiple beancount-files.

However since the update from 1.26 to 1.27 its not possible anymore to load the fava-website.
Instead launching fava results in a white page under the url /beancount/income_statement/.

Any ideas why that happens?

**Comment by yagebu** [comment]
Running with multiple beancount files works fine for me with 1.27 - are there error messages from Fava or in the browser console?

**Comment by gismo141** [comment]
additional info:
I am using yegle/fava as docker-container but since he only bumped the last update to 1.27 that’s why I posted it here.

The docker log seems fine however I haven’t checked the browsers log files yet.

**Comment by floriskruisselbrink** [comment]
If fava is only showing a white page, in my experience that is caused by some ghost or part of an old fava process still listening on port 5000.
For some reason, I don't get an error when that is the case when I start fava and it seems the new instance is running correctly, but I only see a white page.
After killing all processes listening on port 5000 and then starting a fresh instance of fava, everything works again.

My setup: macOS Sonoma, M2 Macbook Pro.

Find all processes that 'do something' with port 5000:
```sh
lsof -i -n -P | grep TCP | grep 5000
```
First number is process-id, `kill <process-id>` kills it. Repeat until lsof shows nothing.

_(I know there are probably better ways to find the processes listening on port 5000)_

**Comment by vishalg** [comment]
@gismo141 - I had the same issue, I was providing multiple filenames separated by a space. Apparently they need to be separated by ; (on windows) or : (on linux). Try 

BEANCOUNT_FILE=file1:file2
