### ISSUE TITLE
Accounts autocomplete is not sorted

### ISSUE THREAD

**Issue by umangv** [beancount/fava#1773]
For example (this is from the output of bean-example, using Fava built at HEAD):

![Screenshot from 2024-03-11 20-22-45](https://github.com/beancount/fava/assets/306547/fb02759c-52e2-437b-8266-2bb5431d5746)

I think I have a fix for this. I'll attach a PR.

**Comment by yagebu** [comment]
This is intentional :) The account list is ranked by how often the accounts are used in transactions (with some exponential decays so that recent transactions could more), see https://github.com/beancount/fava/blob/ad224193eecd69d15a0192d9bfb8da4e673709bc/src/fava/core/attributes.py. That way, the accounts that are most likely to be the ones you want to select should appear more at the top.

**Comment by umangv** [comment]
Ah, thank you. Sorry for the confusion!

**Comment by yagebu** [comment]
No worries - and thanks for already having prepared a PR :)
