### ISSUE TITLE
Budgets: Add support for one-time-budgets

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#375]
Currently the "budget"-directives only allow for recurring budgets. Add the support to specify a one-time budget, eg. for a specific day, week, month or year. 

This should be an addition to the recurring budget. Example: When you specify a specific budget for the account that holds expenses for your car (repairs, etc.), but once every 4 years you need new tires, add the ability to add the special one-time tire expense as a budget entry.

**Comment by yagebu** [comment]
How should these one-time budgets work exactly? Like a daily budget that gets removed on the next day basically and count in addition to the recurring budgets?

**Comment by aumayr** [comment]
The recurring budgets are internally divided up into the days that they represent, eg. "weekly 21 EUR" will become 3 EUR for each day of that week. After that period is over, the difference is reported in Fava, and the budget for this account is "refilled" for the next period (week in the example), until eventually a new recurring budget for this account takes over.

A one-time budget would be set on a specific date, and then become smaller as the days drag on and transactions are made on that account, until it hits zero. At this point, it is not longer "relevant" and is not considered anymore. 

These one-time budgets have to be calculated separately from recurring budgets, as a recurring one does not replace a one-time, and vice-versa.

So in essence this would be a separate budget calculation, not based on fixed ranges, but on one-time "fill-ups" that decline with each future transaction, until they hit zero, at which point they are "done".

Syntax could be:

```ruby
2016-06-01 custom "budget" Expenses:Holiday   "onetime"   2500.00 EUR
# or
2016-06-01 custom "budget" Expenses:Holiday   2500.00 EUR
```

**Comment by rayalan** [comment]
So I just started playing with Beancount/Fava, and this was the first feature in budgeting that I looked for. 

However, I _think_ this gets into the idea that every dollar has an allocation, and money is transferred between budgets. So I budget for, say, an emergency fund, and when my car unexpectedly needs new tires, I "transfer" the money from the emergency budget to the auto repair budget. Or at the end of year, I can look at my gift budget, see that I didn't spend it all, and transfer the remainder into my 5 year anniversary budget. 

This gets into the concept of a comprehensive budget (which I haven't yet seen in Fava) and "virtual accounts" of some sort. For the purposes of a onetime, though, I'd want the code to work like this: 

```
def _matching_budgets(budgets, account_name, date_active):
    """Find matching budgets.

    Returns:
        The budget that is active on the specified date for the
        specified account.
    """
    last_seen_budgets = {}
    one_time_budgets = []
    for budget in budgets[account_name]:
        if budget.period != 'onetime' and budget.date_start == date_active:
                one_time_budgets.append(budget) 
        elif budget.date_start <= date_active:
            last_seen_budgets[budget.currency] = budget
        else:
            break
    return last_seen_budgets.values() + one_time_budgets  
```
which would do it, along with a define in `number_of_days_in_period` to map the period "onetime" to 1 day. Basically, instead of returning a dictionary mapping currency to budget, we just return a list of budgets since we use the budget's currency anyway and ignore the key. We just tack on the onetime budgets so they get counted for a single day at full value, and voila.

I don't know that's a maintainable solution going forward, but it's a starting point.

**Comment by yagebu** [comment]
> A one-time budget would be set on a specific date, and then become smaller as the days drag on and transactions are made on that account, until it hits zero. At this point, it is not longer "relevant" and is not considered anymore.

That's not a budget, which is an amount for a specified time interval, but rather just savings. Also, it would behave completely differently from real budgets and I don't really see how they could be combined in the reports.

I think the following is a better way to handle these unexpected/rare/emergency expenses: If one wants to budget for them, at the end of every month or year one should transfer a certain amount of funds to a savings account marked for that purposes (basically like @rayalan described it). This is all possible in Fava already afaics, I guess it can get a bit verbose so a plugin could be helpful.

> This gets into the concept of a comprehensive budget (which I haven't yet seen in Fava) and "virtual accounts" of some sort.

By comprehensive budget you mean what you described above, or something more complicated? If so, I think that's really possible already, however instead of transfering money from your emergency budget to another budget, you should transfer the money from your emergency fund (which gets replenished from the emergency budget) to pay for the unexpected expense.

**Comment by rayalan** [comment]
> >  This gets into the concept of a comprehensive budget (which I haven't yet seen in Fava) and "virtual accounts" of some sort.

> By comprehensive budget you mean what you described above, or something more complicated? If so, I think that's really possible already, however instead of transfering money from your emergency budget to another budget, you should transfer the money from your emergency fund (which gets replenished from the emergency budget) to pay for the unexpected expense.

What I describe above. I had somehow thought that budgets were only associated with expenses, and since I wanted to track even emergency auto repairs as auto repairs (all the better to have a better budget in the future), I'd assumed I needed to mess with the auto repair expense budget rather than the emergency fund asset budget (which I hadn't realized could even exist). 

I need to play with that capability more; maybe budget transfers aren't nearly as useful then.

**Comment by yagebu** [comment]
In terms of budgeting, the current capabilities in Fava are quite "lightweight". It basically allows you to set a target/average difference per day for an account. Unlike balances it is not "enforced", i.e., violating the budget doesn't produce any errors, it really is just a "display feature".

If one wants to do more involved budgeting, I think it's better to use accounts to track the budgets - 
for example envelope budgeting seems to be popular way of doing budgeting. There are some articles linked on the [plaintextaccounting.org](http://plaintextaccounting.org/#budgeting) website. [This approach](https://frdmtoplay.com/envelope-budgeting-with-ledger/) could be used in Beancount too (with a plugin to generate the automated transactions).

**Comment by aumayr** [comment]
> That's not a budget, which is an amount for a specified time interval, but rather just savings.

That's true. Implementing this with "plain" Asset-accounts is fine for me as well (that is what I do currently). 

So for me, this issue is a "no-fix" and can be closed. 
Please feel free to reopen if you want to discuss this further!

**Comment by Ramblurr** [comment]
@yagebu sorry for dredging up this old issue, but the linked blog post seems to describe a system highly tied to ledger-only features, namely virtual transactions. Am I missing something?

I **really** want to use beancount (for a bunch of reasons) but ynab style envelope budgeting across multiple actual "real" accounts is also something I want.

**Comment by yagebu** [comment]
> ledger-only features, namely virtual transactions

@Ramblurr: it uses virtual postings with brackets, which must balance, and hence can simply be substituted by "normal" postings in Beancount.
