### ISSUE TITLE
Add filter for links

### ISSUE THREAD

**Issue by aumayr** [beancount/fava#403]
Add a filter for links, exactly mirroring the functionality of the Tags filter.

Maybe even unify them into the same filter, where tags show up with a "#"-prefix, and links with a "^"-prefix.

**Comment by yagebu** [comment]
Links and tags basically behave the same syntactically, but I've felt like they are distinguished in the following way semantically (or they should, otherwise it's weird to have two language elements that do the same thing): Tags are useful for tagging lots of transactions, like all transactions from a vacation, or everything tax-related for example; Links to really link a small set of transactions, like one where you borrow someone money with the transaction when you get it back.

So I think linked transactions should only be quite few for a single link so it's not very useful to filter for just one link IMHO and I definitely wouldn't waste any screen space for a filter. I'd find it nicer if clicking on a link would open the journal for that link in a overlay, then you can check out the (few) linked entries and then get back to the current page in an instant. I can implement this if you agree ;)

> Maybe even unify them into the same filter, where tags show up with a "#"-prefix, and links with a "^"-prefix.

That's a great idea! I'd leave the links out of the autocomplete though (with something like the statement plugin I'd think it would get out of hand). If we make these changes to this filter we could also make it support regular expressions, so one could filter for multiple tags/links more easily.

**Comment by aumayr** [comment]
> Tags are useful for tagging lots of transactions, like all transactions from a vacation, or everything tax-related for example; Links to really link a small set of transactions, like one where you borrow someone money with the transaction when you get it back.

That's also how I understand it. For me there are quite a few cases where a set of transactions belongs together. I also want to be able to link Notes and Documents and even Queries, as sometimes all that is necessary to "explain" a certain situation.

> I'd find it nicer if clicking on a link would open the journal for that link in a overlay, then you can check out the (few) linked entries and then get back to the current page in an instant. I can implement this if you agree ;)

For me personally an extra overlay is not necessary, as PR #398 already includes a separate page for a certain link. But feel free to implement this if you feel the need for it ;-)

> I'd leave the links out of the autocomplete though (with something like the statement plugin I'd think it would get out of hand). If we make these changes to this filter we could also make it support regular expressions, so one could filter for multiple tags/links more easily.

Agree heavily with both, and would be very useful!

**Comment by yagebu** [comment]
> For me personally an extra overlay is not necessary, as PR #398 already includes a separate page for a certain link. But feel free to implement this if you feel the need for it ;-)

I find the extra journal too much personally, so my suggestion would be to just have the overlay instead.

**Comment by aumayr** [comment]
> I find the extra journal too much personally, so my suggestion would be to just have the overlay instead.

I'm fine with an overlay.

As I see it the content the extra Journal page in #398 can also be represented when I filter for a specific link, and then show the regular Journal. It would certainly almost look the same, and the suggested overlay would be a shortcut for quickly glancing. 

My only requirement is that this has to be somehow directly addressable by an URL (so it is bookmarkable, etc.), but that would be working with the filter+Journal.
