### ISSUE TITLE
Improved way of displaying metadata

### ISSUE THREAD

**Issue by adamgibbins** [beancount/fava#455]
When I import transactions from my bank I try to retain as much information as possible within metadata. So I add things like bank_id, bank_description etc. This is displayed in fava like so:

![image](https://cloud.githubusercontent.com/assets/46830/21624444/fa340838-d1fe-11e6-8d93-502298b8b783.png)

As all my keys are prefixed with bank so I just get a bunch of ba, ba, ba, ba - not very useful. I can think of two ways to improve this:
- Show the full key + value when hovering over the "ba", currently it just shows the file and line.
- Potentially show the entire key name up to a limit? There's a fair bit of unused space on the transaction line for those without descriptions. Failing that maybe show them when the transaction is expanded somehow?

Thoughts?

Thanks

**Comment by aumayr** [comment]
Showing the whole label when hovering is a good idea and should be easy to implement.

For showing more by default, the idea with using the space could be: Show max. 12 characters in total, so when there are three metadata-keys show 4 characters each. What do you think about that?

**Comment by adamgibbins** [comment]
Sounds good!

**Comment by yagebu** [comment]
> Showing the whole label when hovering is a good idea and should be easy to implement.

👍  . Additionally clicking could show both the postings and the metadata, not just the postings as it does now.

> Show max. 12 characters in total, so when there are three metadata-keys show 4 characters each.

In @adamgibbins's example, this would show exactly the same as it does now, so it wouldn't help much. And for people using fewer metadata keys, it probably won't be that helpful either (I can tell from `st` that there's a `statement` metadata already). Generally just knowing the key isn't that helpful - the value will contain the relevant data, as one should have used a tag instead otherwise. I'm against showing more than 2 characters as it would clutter up the transaction line.

**Comment by adamgibbins** [comment]
@yagebu This doesn't appear to work, I'm still seeing the filename:linenumber on hover?

**Comment by yagebu** [comment]
Are you hovering over the indicators? Works in all browsers for me.

**Comment by adamgibbins** [comment]
Oops sorry, seems I screwed my container regeneration up -- all is good, thanks!
