### ISSUE TITLE
Add ability to clear transactions

### ISSUE THREAD

**Issue by adamgibbins** [beancount/fava#456]
When I import transactions I guess the second leg of the transaction and mark it with a ! flag until I've confirmed it. I generally find browsing the fava transaction screens to be more visually pleasing and efficient than the raw beancount files so I do my reviews in fava, It'd be nice if I could just click the flag to change its status so I don't have to continually alt-tab or click through to the editor + refresh on 100s of transactions.

**Comment by aumayr** [comment]
This seems like a useful feature, but a "hidden" one, because now clicking on the row (and with that the little dots) just expands the row. Maybe an alt-click or ctrl-click could do that. 

More broadly, this also goes into the direction of changing the beancount file directly, which seems to be the direction many of Fava's new features are going. 

@adamgibbins Would you prepare a PR for this?

**Comment by adamgibbins** [comment]
On second thought it'd be pretty nice to make it a keyboard shortcut, that'd keep it out the way cluttering the interface more too.

@aumayr I'd love to, but have written ~100 lines of python ever, and no JS, so it'd take me some while and probably be terrible. But if you can point me in some direction(s) I'd be happy to take a stab.

**Comment by aumayr** [comment]
As this requires the direct manipulation of the Beancount file, some thought has to go into how to approach this (the add-transaction-feature just appends text, but does not change it). 

@yagebu Do you have any thoughts on how to approach this?

**Comment by yagebu** [comment]
#563 should make changing the flag much quicker than before. I don't to edit the flag very often so I won't implement an even more direct way to edit them.

**Comment by GuillaumeHM** [comment]
This subject is still open at  #1151.
