### ISSUE TITLE
fava columns too small for actual values

### ISSUE THREAD

**Issue by hoostus** [beancount/fava#466]
Screenshots:

http://take.ms/klioX
http://take.ms/SrsrQ

It looks like the columns in most places are hard coded to a width that is not sufficient for the values they contain.

**Comment by xentac** [comment]
Unfortunately this is a function of the number of operating currencies you
have. I did a lot of work to try to fit everything on a phone screen in
landscape mode. I'm totally open to suggestions that don't compromise that
screen size.

I had a bug filed preciously to discuss this problem but it was closed
because there was no agreement on how to proceed.

**Comment by hoostus** [comment]
But I can't even have *two* operating currencies or the layout breaks.

The layout doesn't seem able to cope with numbers greater than 100 million. Unfortunately, given exchange rates, it is relatively easy to have accounts in Vietnam dong greater than that. (1 billion VND = $50,000 USD)

Is there a link to the previous discussion, so I don't rehash old arguments that have already been proven dumb? 😄

**Comment by ngoonee** [comment]
What I've seen done with the DataTables javascript implementation is for overly long columns to overflow (and a plus button shows up which will show the values). Not terribly usable though, to be fair.

**Comment by hoostus** [comment]
I found the old issue (I think): https://github.com/beancount/fava/issues/385

A summary, as I understand it:

With a single operating_currency, there are no issues up to 11 digits. (9 before the decimal + 2 after = hundreds of millions). When you get to 12 digits things are a bit cramped but still workable.

(Unfortunately, these are not my real account balances 😭 )

![image](https://cloud.githubusercontent.com/assets/170288/21877134/9121545e-d8bb-11e6-9fb8-1422dbe4e889.png)

But when you add in a second operating_currency, problems start much sooner. At only 9 digits (7 before the decimal + 2 after = single digit millions).

![image](https://cloud.githubusercontent.com/assets/170288/21877171/cae2f634-d8bb-11e6-8fb9-c0da1375a8fe.png)

I'd say the primary problem is trying to display multiple operating_currencies at the same time, especially in mobile. I'm brand new to beancount so I'm not totally sure how/why people use multiple operating currencies. But based on my own use cases, I basically never *need* to see them side-by-side like that.

It feels like the operating_currency is conflating two things: which currencies to do conversions between and which currencies to display when reporting. That's somewhat understandable coming from the plaintext, single-file world. But how about making the list of operating_currencies simple a choice for reporting rather than the fixed list. Maybe something like this for a web-based view like fava:

* All reports are only shown in a single currency.
* The list of possible currencies is defined by the list of operating_currencies.
* The user is able to switch between available currencies. I'm not sure where a good place for this would be. Right now at the top it already lists all operating currencies, so maybe that could become a radio button type thing.
* Store the user's choice in localstore/cookie/whatever so they don't have to select it every single time. Right now things like the toggle state doesn't seem like it is persisted, so those could also be wrapped in the same storage.

Now that I think about it, if the list of operating_currencies becomes selectable, maybe there's no reason to prevent a user from select multiples. If they want to scroll, let them scroll.

**Comment by hoostus** [comment]
A possibly related issue is that the Other column is taking up 8rem for me even though there is no data in it.  The check in _tree-table.html looks like

`(operating_currencies|sort != api.options['commodities']|list|sort)`

But it seems like checking against *all* commodities in api.options is overkill. What we really care about is "are there any commodities that can't be converted to an operating_currency?" Is there a way to check that in beancount?

**Comment by aumayr** [comment]
> I'm brand new to beancount so I'm not totally sure how/why people use multiple operating currencies.

I do use multiple operating currencies, as I have transactions in both all the time. Other currencies that I do not use regularly I do not use `operating_currency` either - just for the two I use all the time.

> localstore/cookie/whatever

No localstore/cookie (aka no "state") for Fava - just use the URL and all it's features (path, query hash, params). 

> It feels like the operating_currency is conflating two things: which currencies to do conversions between and which currencies to display when reporting.

Conversions are possible between all currencies, not just operating currencies. As I understand it, this option in fact _is_ primarily for displaying purposes (also see `bean-web`).

What we could do is try to calculate the width of the column based on it's content. I know this is a hackish way of fixing this, but as so many different currencies are used (I saw at least 6 different ones in different Fava issues alone), and the spacing/column width is a real issue for some.

**Comment by xentac** [comment]
No matter what, 3+ currencies will be impossible to fit on a phone screen
in landscape mode, regardless of dynamic column sizing.

**Comment by hoostus** [comment]
I agree that dynamic sizing, while it would help slightly, isn't a full solution.

We could bump up the default spacing -- but that comes at the cost of wasting space for most currencies/situations. So dynamic sizing would help a bit with that -- scenarios where you have two currencies with very different amounts (maybe I have 5,000.23 Singapore Dollars but 6,123,543.89 India Rupees).

For my personal use case, I basically never care about all three operating currencies at the same time, so I'm struggling to understand why someone would want that behaviour, especially on a mobile device. What's the user problem that would solve?

**Comment by yagebu** [comment]
I personally only use one operating currency most of the time, but I think that for two the layout should still work well. For three or more, I think it's acceptable that the user might have to scroll on a mobile or only have one column on a desktop. I'm not a great fan of dynamic sizing of the columns - having columns of all different widths wouldn't be beneficial for the layout and it also seems annoying to implement.

I've opened a PR with some changes towards addressing this issue: #475.

I don't have huge amounts in my currencies, but if I had millions of something, I wouldn't care if it's a few hundred more or less, so using a SI-prefix to shorten the displayed number (the exact value could still be shown on hover) could help reduce clutter.

> But how about making the list of operating_currencies simple a choice for reporting rather than the fixed list. [...]

The only intended meaning of operating_currencies is for reporting, so that's what it is already. I'm strongly against hiding any currencies, the reports should always satisfy the basic accounting equations IMHO.

**Comment by xentac** [comment]
As a Canadian currently living in the US, I use CAD and USD as operating currencies and have assets with both as the cost basis.  I definitely want them all to show the way they are in fava.

I've considered the side scrolling option (while keeping the account name pinned, sort of like a spreadsheet can do).  My concern was that you'd still only be able to see about 2 columns.

SI is an interesting idea that I hadn't thought of.  I had assumed we were using fixed width fonts because we wanted digit columns to line up.  That could probably solve the problem in the short term.

**Comment by yagebu** [comment]
With the changes I've made in #475, the tables should approximately still have the same width (for 1 or 2 operating currencies) but the number columns should be able to contain maybe 2 more digits (for 2) and for more currencies the whole page just gets wider. Comments on those changes would be welcome!

**Comment by yagebu** [comment]
This issue mostly seems to be addressed with #475.
