### ISSUE TITLE
Account journal balances always show the same value

### ISSUE THREAD

**Issue by xentac** [beancount/fava#474]
Possibly this happened around the time that the journal reordering happened.

**Comment by aumayr** [comment]
I can confirm this bug - same for me on current `master`.

**Comment by yagebu** [comment]
This is due to `realization.iterate_with_balance` always yielding the same Inventory object as balance, so if generate a list to reverse it, we only get the final balance.

@blais: Could you change the `iterate_with_balance` function so that it yields a shallow copy of the `running_balance` inventory?

**Comment by blais** [comment]
That's the better solution IMO.
Thanks,
