### ISSUE TITLE
Add option to enable auto-reload

### ISSUE THREAD

**Issue by SirVer** [beancount/fava#484]
Can I get my autoreload back, please?

**Comment by aumayr** [comment]
What exactly are you missing?

**Comment by SirVer** [comment]
Fava detects changes in the underlying beancount files and since recently just autoreloaded the current page. I really thought that was a terrific experience and meshed well with my edit-analyze cycle.

Since recently (I do not know the exact SHA), fava instead displays a banner "Changes detected. Click to reload." which is what I think is an ergonomic step back to earlier behaviors. I'd like to get the old behavior again, either through an option or by reverting.

I am sorry that I did not make this clear.

**Comment by aumayr** [comment]
@yagebu Can you elaborate on why this change was introduced?

**Comment by yagebu** [comment]
This is not a very recent change, the behaviour hasn't changed since v1.0. I think the current behaviour is a preferable default behaviour compared to auto-reloading. One might be looking at for example a long journal/the charts and not want to lose some page state due to a reload. Also, due to the way the document folders work (we have to monitor the whole folder), there can be a lot of noise that might not actually warrant a reload.

In places where we respond to user interaction like a documents upload or adding a transaction we can do a reload but otherwise the decision whether the page will be refreshed should be left to the user IMHO. An option to enable auto-reload would be fine, of course.

**Comment by aumayr** [comment]
> An option to enable auto-reload would be fine, of

**Comment by SirVer** [comment]
Thank you!!!

**Comment by senorsmile** [comment]
> I think the current behaviour is a preferable default behaviour compared to auto-reloading.

I agree.  I much prefer the current way of displaying a notification that lets me know that a reload is necessary, but has NOT yet taken place until I click said notification.
