### ISSUE TITLE
Errors don't auto reload

### ISSUE THREAD

**Issue by adamgibbins** [beancount/fava#532]
I have auto-reload set to true, yet I have to refresh my browser to get errors to vanish from the sidebar. Is this fixable or is this by design for some reason?

**Comment by yagebu** [comment]
So the main page content auto-reloads but the sidebar doesn't? That's odd since after f4c0e6608e028875bf4d9ff0ca1b2691eb4cd51e the function that reloads the sidebar is called before the one that reloads the page content.

**Comment by xentac** [comment]
I think it's not the refresh action, it's everything else.

Steps to reproduce:

1. Create error in file
2. Wait for yellow refresh button and red error item in menu to appear
3. Click any link other than the refresh button

Expected behaviour:

Errors disappear after the rest of the page has been updated (as it used to do when the entire page refreshed on every link).

Actual behaviour:

The rest of the page has been updated, but the (now) inaccurate errors are still counted.

Refreshing the page or going to the errors page will remove the red link.

**Comment by yagebu** [comment]
So if one moved to a page before Fava noticed that a file has changed, the sidebar wouldn't reload. Now the number of errors is updated on every page move to, so this should really be fixed.

**Comment by xentac** [comment]
This is actually a worse situation now...

Errors always shows in red, even when the number is 0 and any autoreload of the sidebar causes a 404 error and the sidebar turns into a big error message.

**Comment by yagebu** [comment]
You need to rebundle the Javascript code.

**Comment by xentac** [comment]
I just tried on a different machine and I think it might have been the opposite problem.  The new machine doesn't have any problems, but the old one possibly was using an older cached js file.
