### ISSUE TITLE
Minimum system requirements

### ISSUE THREAD

**Issue by mariosangiorgio** [beancount/fava#582]
Hello,
after using fava for a while on my laptop I tried to install it in a Raspberry Pi Model B.

I installed it via pip and it works, but it is extremely slow.
Page take a few seconds to appear and `fava` uses 100% of the CPU while it's generating them.

I see that there is a command line option to run fava with a profiler but before I start looking into this I wanted to check if it's expected to work on machines with such low spec.

**Comment by xentac** [comment]
I've been looking at profiling a little bit so far. I sped up the journal
pages some. Now I'm trying to speed up the tree tables (balance sheet and
income statement).

The main problem is that the processing of a single request happens on a
single thread. To build a particular page, we often have to walk the
entries list (your list of transactions), or subsets of it, multiple times.
I'm trying to think of different algorithms, precomputations, or
parallelization we could do but it's not the easiest of problems.

The data model is really easy to work with because it's mostly lists and
aggregations of lists, but it doesn't really lead to efficient accesses.

Feel free to give it a shot.

**Comment by yagebu** [comment]
Fava does not have any real minimum requirements as the performance depends on the size of your Beancount file and "fast enough" is subjective. Any help improving Fava's performance is very welcome! I presume that for a lot of the performance-critical parts we use functions from Beancount though (the startup time is mostly the parsing time in Beancount for example). There's been some discussion about Beancount's performance on the mailing list: https://groups.google.com/forum/#!topic/beancount/rmc8X6iB3gw

**Comment by mariosangiorgio** [comment]
Thanks for the link, I'll have a look an when I have some spare time I'll try to have a look at the code and at the profiler output I collected.

If you are interested in having a look at the profiler output form the run on the Raspberry Pi, I can share it with you. My file is not that big (it has 2064 postings) but that's compensated by the slowness of the hardware.

In the meantime I am keeping using fava from my laptop, where everything is way more responsive.

**Comment by xentac** [comment]
I'm hoping to have https://github.com/beancount/fava/pull/583 ready for
submission in the next few days, which should speed up all tree table pages
(but especially the balance sheet) on the raspberry pi.

**Comment by mariosangiorgio** [comment]
@xentac that's great!
