### ISSUE TITLE
Book value vs Market value in account trees

### ISSUE THREAD

**Issue by yagebu** [beancount/fava#589]
In the discussion on #588, the question of whether we should display balances in the account trees at cost (as we currently) or at market value came up. The reports in Fava go back to the reports in `bean-web` and I don't think there's been any real discussion on this issue so far. Let's take the following example entries.

    2017-01-01 * "Invest"
      Assets:Checking
      Assets:Investment 10 HOOLI {5 USD}

    2017-02-01 price HOOLI 6 USD

 As far as I can see we could display the balances (of `Assets:Investment`) in the following way:

1. Display them at the historical cost (`50 USD`). This is what we currently do (when "At Cost" is selected in the dropdown).
1. Display them at market value (`60 USD`) and post the difference to `Equity:UnrealizedGains` or something.
1. Display them at market value (`60 USD`). This is currently possible by selecting "At Market Value" in the dropdown.
1. Display the units (`5 HOOLI`).

I do quite like 1. as a default. 1. is maybe closest to the traditional accounting approach as it's following the historical cost principle (I'm not an expert on accounting, so this should be taken with a grain of salt of course).  2. is also useful and it's currently not possible to get this sort of report in Fava directly, but the unrealized gains plugin does offer this (however it only adds unrealized gains once at the end of all entries not for any possible filtered interval).

Having 3. or 4. as a default would be quite far from the typical notion of a balance sheet. 3. is already possible and has a simple implementation as nothing has to be moved around to balance things out. The holdings page somewhat handles 4. but maybe it would also be nice to have it in the account tree.

Which of these options should Fava offer and which should be default?

Pinging and quoting @blais from the other discussion:

> I would argue for displaying them at market by default,
and to add an option (a toggle?) to display at book value.

> [..] I'd have reported at market value and added a tax
liability to account for taxes on the unrealized profit, so that the
balance reflect the value on liquidation.

**Comment by xentac** [comment]
Option 2 is something that I tried to better support with unrealized_periodic (https://github.com/xentac/beancount-plugins-xentac/blob/master/beancount_plugins_xentac/plugins/unrealized_periodic.py) but it broke net worth calculation.

The correct way to do it is add unrealized transactions every time a Price shows up in the entry table, then use that list instead of the unmodified one when building the tree and journal (but not the net worth table). I suppose, on load, we could build the market value entry list and store it as another attribute in FavaLedger. From there we would remove the current At Market Value query and instead just use the different list of entries.

Possibly now that I understand better how Inventory objects work, I may be able to write a more efficient version of unrealized_periodic that could be used to build that list in Fava. Given that it only would run on initial load, it probably wouldn't end up with too bad of an experience.

**Comment by xentac** [comment]
Note: With Option 2, if you do as I propose, you'll want to calculate the at cost value instead of the market value for table rendering.

**Comment by cceckman** [comment]
At the very least, (4) should be an option- the account doesn't have 60 USD in it, nor 50 USD, it has 5 HOOLI (with a cost / value of some USD.) I'm kind of surprised that "balance sheet" doesn't imply that as the default, but that's my naive reading of the term. :-)

If the idea of the balance sheet is generally to show net worth (per https://github.com/beancount/fava/issues/588#issuecomment-330244723), then having market value as the default makes the most sense IMO.

**Comment by xentac** [comment]
Doesn't the holdings page show you all the holdings in all your accounts?

**Comment by cceckman** [comment]
Yes, it can show a summary view ("Holding by account") that summarizes by account. (Thanks for the pointer- I'm new to Fava, don't know where everything is yet.)

**Comment by xentac** [comment]
I have a module now that looks to generate proper unrealized entries (on load) every time the price or inventory changes. I'm trying to figure out how to seamlessly map it into the chart generation. My plan is to track down all the income statement, balance sheet, and trial balance trees and make the decision at that point.

Is there anywhere else I should look into?

**Comment by yagebu** [comment]
> unrealized entries (on load) every time the price or inventory changes

This seems like it would be horribly inefficient. In my case it would increase the number of entries by a few orders of magnitude. This should really be done at chart/tree generation time.

**Comment by xentac** [comment]
Load only happens when the ledger file changes, chart generation is a more
interactive operation, isn't it?

**Comment by xentac** [comment]
In addition, filtering and calculating monthly change and balance works
unmodified.

**Comment by xentac** [comment]
I would rather optimize for page response times than startup/load times. I plan on profiling my strategy soon, just working on the proof of concept now.

In cases where you don't want the market value, you use the original all_entries list which is still untouched. This is a parallel list of entries when you want to render something at market value instead of at cost or otherwise.

**Comment by xentac** [comment]
How often do you update prices and how many entries do you have in your ledger? My ledger's all_entries member has 11447 rows, the market value entry list has 20340 rows. I only have full data from 2016 till today, but I update my price map most weeks and because of Betterment (which I have data from since I started in 2015-05) I have a lot of commodity trades in that time.

Mostly I was looking for a straightforward way of hooking unrealized transactions in every place without having to keep track of each rendering step (like monthly changes and balances). I figured that a canonically correct implementation was better than something integrated in every place we evaluate a market value.

I'm not convinced that your proposed implementation will be faster. To calculate unrealized gains, one must create an Inventory from all relevant entries, create and aggregate Holdings, then look up the price. This must be done at the account level to be rendered in templates, sometimes this is fine when trying to fill in a field (like in a tree table), but other times it involves periodic evaluations (like in monthly changes and balances tables). The most time consuming part is the collection and aggregation of commodities not the price lookup. I have done my best to make an efficient unrealized transaction generator.

**Comment by yagebu** [comment]
The commodities I have are mostly long-held and for most of them I have daily prices for a few years. So instead of, say, a few dozen entries per commodity I'd have a few hundred or thousand market value entries.

> The most time consuming part is the collection and aggregation of commodities not the price lookup.

We still have to aggregate just as much and only save the price lookup if we have these market value entries, no? I guess I'm slightly misunderstanding what these entries would look like. But let's maybe take this off-topic discussion not any further here - performance improvements are somewhat unrelated and always welcome.

> At the very least, (4) should be an option- the account doesn't have 60 USD in it, nor 50 USD, it has 5 HOOLI (with a cost / value of some USD.) I'm kind of surprised that "balance sheet" doesn't imply that as the default, but that's my naive reading of the term. :-)

I think it makes sense that it doesn't show 5 HOOLI - the balance sheet tries to give you an overview of your financial situation and it doesn't really matter if you've got 5 HOOLI or 10 APPLES but rather how much those are worth in USD. Of course knowing the balance in "units" is interesting too but we should use other reports for that.

I've got an (IMHO) better suggestion on how to display market value (2.). I think we could use a similar display as we do for the budget to display the market value and the unrealized gain next to it:

![screenshot-2017-9-28 ausgaben essen - jakobs ledger](https://user-images.githubusercontent.com/2482259/30979828-3131c020-a47f-11e7-9d0d-cc3ca7e97b35.png)

Shouldn't be a big change, will see to implement that over the weekend.
