### ISSUE TITLE
Additional Opening-Balances account shown in Balance Sheet

### ISSUE THREAD

**Issue by ngoonee** [beancount/fava#596]
Am running a few months behind version wise in fava, but I don't see any reports of this so possibly it's not fixed yet. My Balance Sheet shows a phantom (zero value) Equity:Opening-Balances account which is not in my beancount file. bean-web doesn't show this account (my actual account is named Equity:OpeningBalances)

**Comment by yagebu** [comment]
The name of this account is determined by the `account_previous_balances` options, which is Opening-Balances by default. So you should set that to OpeningBalances. If no time filter is set, it might end up empty (apart from the "real" opening balances at the start of your file) but if a time filter is set, all previous entries will be summarised into that account so that the balance sheet balances.

**Comment by ngoonee** [comment]
Interestingly enough, the account does not show up if I DON'T set a time filter, only if I do. Either way, it has no numerical value. Is that supposed to be how it works?

**Comment by yagebu** [comment]
If you don't set a time filter, there's no entry on that account, so it doesn't "exist". If a time filter is set that account will have entries (that might sum up to zero) so it will show up (of course depending on the fava-options regarding which accounts to show).

**Comment by ngoonee** [comment]
Okay that's clear then, thanks.
