### ISSUE TITLE
Date dropped from _serialize_account_node when calculating cost

### ISSUE THREAD

**Issue by xentac** [beancount/fava#613]
https://github.com/beancount/fava/blob/037f188602ca9511a951612330ae5fea260dbf65/fava/core/charts.py#L55

I'm pretty sure that this means At Market Value pages always show newest price, not price at the end of the filtered time. I noticed because I just extended the depreciation schedule of my car and it's showing me December 2018 value no matter my filters.

**Comment by shaotongwang** [comment]
The "Converted to commodity" views also use the newest price data instead of price data at an appropriate date.

I think it makes the most sense to convert asset and liability accounts using the price data at the end date of the filtered time period, and convert postings in income and expense accounts using the price data at the date of the transaction. To balance, post to Equity:Conversions for commodities not held at cost and post to Equity:Unrealized for commodities held at cost.

Equity:Unrealized should also be split into Unrealized:Current and Unrealized:Previous as with the other generated equity accounts.
