### ISSUE TITLE
Advanced filter syntax

### ISSUE THREAD

**Issue by yagebu** [beancount/fava#632]
The current filters in Fava allow for quite some flexible filtering already, the page header is already quite crowded though, so it's hard to add more input fields to address something like #603.

I propose to replace the FROM, tag, and payee filter with a single input which supports a flexible filter syntax, implemented in #631.

It can be described by the following grammar:

    filter : expr
           | <empty>

    expr : expr expr
         | expr ',' expr
         | '(' expr ')'
         | '-' expr
         | simple_expr

    simple_expr : TAG
                | LINK
                | KEY STRING

The first two options for `expr` denote conjunction and disjunction respectively, the `-` means negation. The tokens `TAG` and `LINK` are self-explanatory, `KEY` is something like `payee:` and string is `"string"` or `'string'` or `string_without_spaces`.

The strings can be exact matches or regular expressions. Does this seem sufficient?

**Comment by zacchiro** [comment]
What would the valid values for `KEY` be, in addition to `payee:` ?
I'm assuming that all metadata names would be allowed, because that's what would be needed to address #603. Can you confirm?

As a totally unrelated nitpick, it looks like the `:` should be a fixed literal in the grammar, rather than a part of `KEY`, but maybe I'm missing some other use you'd like to make in the future of `KEY`.

With many thanks for your work on this!

**Comment by yagebu** [comment]
> What would the valid values for KEY be, in addition to payee: ?

Anything that's either an attribute of the entry or a metadata key. (the metadata part isn't implemented yet).

> As a totally unrelated nitpick, it looks like the : should be a fixed literal in the grammar, rather than a part of KEY, but maybe I'm missing some other use you'd like to make in the future of KEY.

If the `:` is not part of `KEY`, then the regexes for `STRING` and `KEY` overlap.

**Comment by xentac** [comment]
I think I agree with Stefano, but mostly it's semantic. The simple_expr key
line should be something like

KEY ':' STRING

Where KEY is a string without spaces only (attributes and metadata ids
can't have spaces, right?). A proper lexer would treat the entire unit as a
simple_expr with 2 elements.

Otherwise your definition means you need a different type

key_expr : KEY ':'

Which looks a not weirder to me.

Since you're parsing with regexps, the distinction is mostly moot.

**Comment by yagebu** [comment]
Just like a tag without the hash, a key without the colon doesn't have any use in the grammar. And to reiterate, a key without the colon is a valid string, so the tokens would be come more ambiguous.

**Comment by yagebu** [comment]
This is now implemented (#631), if you have any suggestions on the syntax or any ideas for improvements, feel free to comment here or open a new issue.
