### ISSUE TITLE
Error in app.js in latest version when proxying

### ISSUE THREAD

**Issue by jmgilman** [beancount/fava#637]
Fava Version: 1.6
Python: 3.5.2

Nginx config:

	server {
		listen 80;

		add_header Strict-Transport-Security max-age=2592000;

		server_name fava.gilman.io;

		location / {
			proxy_pass http://127.0.0.1:4180;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Scheme $scheme;
			proxy_connect_timeout 1;
			proxy_send_timeout 30;
			proxy_read_timeout 30;
		}

		listen 443 ssl; # managed by Certbot
		ssl_certificate <redacted>; # managed by Certbot
		ssl_certificate_key <redacted>; # managed by Certbot
		include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

		if ($scheme != "https") {
			return 301 https://$host$request_uri;
		} # managed by Certbot

	}

I'm using OAuth2_Proxy as the redirect. The relevant config section:

    ## the http url(s) of the upstream endpoint.
    upstreams = [
         "http://127.0.0.1:5000/"
    ]

Here is the error that Chrome is throwing whenever I open up any page:

![image](https://user-images.githubusercontent.com/2308444/34843958-ced1e14c-f6c4-11e7-9243-249a5e65b7cf.png)

I can confirm that running this without the proxy resolves the issue. Also, this configuration **was working** in version 1.4 and I only started encountering this after upgrading to 1.6 (Uninstalling 1.6 and reinstalling 1.4 resolves the issue). I also tried updating to 1.5 and I have the exact same error. No configuration changes were made during the upgrade and both nginx and the oauth proxy were not updated (still running same versions).

The result of the error is that most of Fava is broken. The editor doesn't load correctly (no formatting, broken buttons) and none of the popups are working correctly.

I know that other users here use a similar proxy setup, is there some configuration changes I need to make to resolve this?

**Comment by xentac** [comment]
Open up the chrome inspector and check out the network tab. Are any
resources failing or cached?

What I suspect is happening is that one of your secondary resources is
cached and instead of receiving the proper javascript or html, you're still
seeing the oauth proxy authentication page.

Alternatively, you could give me access (xentac@gmail.com) to your
fava.gilman.io to see if I can recreate the issue.

If it is caching related, you could try clicking the "Disable cache"
checkbox on the Network tab of the inspector and try reloading again. You
could also go to the Application tab under "Clear storage" and click "Clear
site data". That will cause your browser to request all resources again at
least once.

**Comment by jmgilman** [comment]
Yes, it was indeed caching. I'll have to add that to my notes next time I upgrade, thanks!
