### ISSUE TITLE
Don't show duplicate entries in query history

### ISSUE THREAD

**Issue by tbm** [beancount/fava#655]
Just experimenting with Fava and I click on the first query and run it again.  As a result, the query shows up in the list twice.  Not knowing what I'm doing, I click it again.  Now the history has the same query three times at the top.  Being a monkey I do this until the whole screen is the same query.

I guess there's an argument for just presenting the query history as it is, but I think it would be more usable if you would only show 1 instance of the latest query (maybe as long as the output hasn't changed).

I'm not saying all duplicates should be filtered everywhere but I think for the first entry it makes sense to remove duplicate entries if they immediately follow the first entry.

**Comment by yagebu** [comment]
> I click on the first query and run it again. As a result, the query shows up in the list twice. Not knowing what I'm doing, I click it again. Now the history has the same query three times at the top. 

That's not what happens though - if you stay on the page, the same query box just gets reopened.

I'd be fine with removing duplicates, but then removing all of them is better. Having more past queries there for reuse is more useful than having the exact query history I think.

**Comment by tbm** [comment]
I can't remember exactly what I did. It's possible I clicked on the query tab, i.e. reloaded the page.

But maybe removing duplicates everywhere is the best way to go. What if the output changed, though? It probably makes sense to remove duplicates only if the query string plus output are the same.

**Comment by yagebu** [comment]
There's two things that can happen when you click on an item in the query history: 1) if you've run the query without leaving the page in between, it will just reopen the box - no rerunning the query, no changing of history, 2) otherwise, the query is run and added to the history (and a box is added on the page). The list of active boxes is independent of the query history, so in case of 2) you'll still be able to produce duplicates.

There's no way to determine if the output changed, so if you changed the file, just reload the page.

**Comment by tbm** [comment]
Thanks!
