### ISSUE TITLE
Split Narration/Payee

### ISSUE THREAD

**Issue by tbm** [beancount/fava#656]
In Beancount, narration and payee are treated differently, including bean-query.

In Fava's journal, the two are combined into a Narration/Payee. This means that you can only sort on that combined string, not on payee and narration separately.  I therefore think they should be split.

I see two arguments again splitting them:

* It will use up more real estate, which could be a real issue.
* Sometimes the payee is empty but then you just have an empty string.

Maybe you have an idea on how to solve the first issue.

**Comment by yagebu** [comment]
The journal allows for sorting of the description column (because it was trivial to implement in addition to date-sorting), but since all different kinds of entries use that column I'd be against splitting it up.

For a sortable table displaying both payee and narration separately, the query shell is the right place IMHO.

**Comment by tbm** [comment]
Ok, feel free to close (or to leave it open for a few weeks in case other people have comments).
