### ISSUE TITLE
Check transactions for errors before saving

### ISSUE THREAD

**Issue by tbm** [beancount/fava#657]
I edit a transaction in Fava and make a syntax error, e.g.:

> 2016-04-21 * ? "Buy some more shares of Hooli"

I click on "Save" and immediately the "Errors" tab lights up.

Could you check for errors when pressing "Save" and show the error immediately while you still have the transaction open.

Possibly you could check after each keystroke but maybe that's too resource intensive (I guess this would be possible when you edit a single transaction rather than the whole file).

**Comment by yagebu** [comment]
There's many ways a transaction can cause an error - checking for it takes too long. So it would only be really viable to check for syntax errors. The syntax is simple enough that they should rarely happen (I can't remember the last time I made one). So to only save a few seconds in these rare cases is not really worth the effort I think (and the amount of additional logic that will have to be maintained). I would be swayed by a PR, otherwise I'd consider this a wont-fix ;)

**Comment by tbm** [comment]
Feel free to close :)

The idea was just to run bean-check but please close if that doesn't make sense.

**Comment by yagebu** [comment]
> The idea was just to run bean-check but please close if that doesn't make sense.

Checking for all kinds of errors would involve saving the file, reloading it, and resetting it in case of errors - that's just a lot of places were something could go wrong and screw up the file (in particular in cases where there's already been errors before).
