### ISSUE TITLE
Stacked charts

### ISSUE THREAD

**Issue by yagebu** [beancount/fava#716]
As suggested by @vlaci in #258:

> I think a stacked bar chart would make sense e.g. for the Monthly Changes graphs. That would make much easier to see the dynamics how accounts' contributions changed from month to month to the expenses

Just like in the treemaps and sunburst charts, amounts of the opposite sign than expected from the account (e.g. a negative value for some expenses subaccount) are problematic and will just get ignored. Alternatively they could be displayed under the x-axis I guess.

**Comment by yagebu** [comment]
Some ideas from #1251:


> Studying how expenses change over time (trying to pinpoint where a rise in expenses came from currently requires flipping back and forth between the top-level expenses chart and charts for expense sub-accounts)

> Visualizing market value of investment portfolios relative to cost basis over time

> [This is another cool example](https://imgur.com/a/0eDD9KE) of a stacked chart that I've been wanting to replicate in Fava.

**Comment by aclindsa** [comment]
@yagebu (bringing discussion here from https://github.com/beancount/fava/issues/1251):

> I guess this could be implemented quite similarly to the existing charts, trying to have the new data structures that are generated by Fava align with the existing ones (in some sense the data required is a combination of the existings hierarchical account charts and the time series charts).

I haven't dug into the code to be certain, but I wonder if the necessary data structure already exists. I noticed that if I add `&conversion=units` on some reports (the Balance Sheet, for example), the line chart appears to simultaneously show the number of units I have of different commodities, varying over time. I think that is the same "shape" of data you would need for a stacked bar chart, right?

> If possible, I think it would also be good if these new charts are not entirely new charts (in terms of the code generating the charts) but we add this as an additional feature to the existing code.

By this, do you mean that you believe the existing bar chart code could and should be modified such that all bar charts become 'stacked' in a way? (And that the bar charts which exist today would then become special cases which happen to only have one data series)

**Comment by aclindsa** [comment]
@yagebu I've come up with some other design questions while thinking about this, and would appreciate your opinion:

When visualizing an account hierarchy with a stacked chart, it is easy for there to be too many accounts to display them all in a meaningful way. I see two potential approaches to address this: 1) Combing accounts with values less than a certain threshold into 'other' and displaying it as the combined total of the smallest accounts, and 2) Rolling amounts belonging to sub-accounts beyond a certain depth into their parent accounts. Perhaps a combination of the two could also be used.

Of the two options, I find 2) more attractive because it allows you to 'drill down' into an account hierarchy in a way which mirrors how the user set it up (and is therefore likely to be intuitive to them). However, it then becomes potentially desirable to come up with a way to quickly navigate to a chart only sub-accounts of a higher-level account (maybe by clicking on that higher level account's section in a top-level stacked chart?). For example, if I see that 'Expenses:Insurance' went up in a certain time period when looking at a stacked bar chart of all my expenses over time, but can't see the sub-accounts under it, I may want to be able to quickly navigate to a similar chart for all sub-accounts of 'Expenses:Insurance' to be able to find that 'Expenses:Insurance:Medical' is ultimately what caused the increase. Is that idea interesting to you, or is that getting to be too complex? Having implemented interactive charts like that elsewhere, I found them quite useful, but am not sure how well they fit into your overall design.

**Comment by yagebu** [comment]
Implemented in #1408
