### ISSUE TITLE
editor doesn't let me leave after an unsaved change

### ISSUE THREAD

**Issue by tbm** [beancount/fava#764]
I enter the editor, I make a change, I click on "journal" or some other link.  I get:

```
There are unsaved changes. Are you sure you want to leave?
```

I click "Ok" and nothing happens. I'm still in the editor.

**Comment by tbm** [comment]
Actually, this looks like a browser issue (Firefox). I get the same problem when I try to delete a comment on GitHub and it asks me to confirm.  So I guess something in my browser is broken.

I don't have this issue with Chrome.

**Comment by ljani** [comment]
@yagebu: Could this be reopened?

I did some debugging:
- On Firefox, [this check](https://github.com/beancount/fava/blob/a8c4f03c1a3b2a5c452858b71b84887782e91602/frontend/src/editor/SourceEditor.svelte#L30) fails, because the strings have different line endings.
    - `value` has Windows style line endings `\r\n` whereas the `editor.getValue()` normalizes them to Linux style line endings `\n`
- Calling [`setValue`](https://github.com/beancount/fava/blob/238aede5b57be206ab5619f4db19d0cba080ade7/frontend/src/editor/Editor.svelte#L11) will not [reset `isClean`](https://github.com/beancount/fava/blob/a8c4f03c1a3b2a5c452858b71b84887782e91602/frontend/src/editor/SourceEditor.svelte#L58), please see [the documentation for `isClean`](https://codemirror.net/doc/manual.html#isClean):
> Returns whether the document is currently clean — not modified since initialization or the last call to markClean if no argument is passed, or since the matching call to changeGeneration if a generation value is given.
- You should be calling [`changeGeneration`](https://codemirror.net/doc/manual.html#changeGeneration), if the data is coming from the backend and you're setting up pristine state. I'm not 100 % sure I can follow where [`value`](https://github.com/beancount/fava/blob/a8c4f03c1a3b2a5c452858b71b84887782e91602/frontend/src/editor/SourceEditor.svelte#L22) is updated, so I'm not really eager to make a PR.

I'm running Firefox 85.0b9. I'm running Fava 1.18 on Windows as well.

Thanks for your work on this useful project!

**Comment by ljani** [comment]
Alternatively, [it seems one could pass line endings to `getValue()`](https://codemirror.net/doc/manual.html#getValue).

**Comment by yagebu** [comment]
I guess the linked to check https://github.com/beancount/fava/blob/a8c4f03c1a3b2a5c452858b71b84887782e91602/frontend/src/editor/SourceEditor.svelte#L30 just shouldn't be in that file, it only makes sense in the other editor Svelte components that might have their value externally set.

I'm in the process of rewriting the editor with Codemirror 6 and during this rewrite I already independently fixed that.

**Comment by yagebu** [comment]
This should be fixed now thanks to the editor rewrite
