### ISSUE TITLE
Google dependencies?

### ISSUE THREAD

**Issue by TRSx80** [beancount/fava#791]
First off, I don't want to get off on the wrong foot, I think you guys are doing awesome work here! I really appreciate everyone's effort, and fava is a really really nice front end for slicing and dicing the Beancount data. :)

But what is up with these Google dependencies? I realize they are probably Beancount dependencies, and get pulled in when Beancount gets pulled in, however...

After installing Beancount I had removed all of them by doing:

`$ pip3 freeze | grep google`

followed by:

`$ sudo pip3 uninstall google-api-python-client`
`$ sudo pip3 uninstall google-auth`
`$ sudo pip3 uninstall google-auth-httplib2`

However after seeing them get installed again when installing fava:

`Successfully installed ... google-api-python-client-1.7.4 google-auth-1.5.0 google-auth-httplib2-0.0.3 ...`

I tried again to do `pip3 uninstall` only to get the following:

`Cannot uninstall requirement google-api-python-client, not installed`

Which I do not understand?

Now I will admit I do not know a lot about Python, however these error messages seem conflicting to me? Perhaps someone can shed some light on that?

I feel that I must state that I have gone out of my way to avoid anything to do with Google. I have installed plain vanilla AOSP (LineageOS) on all of our phones, we run our own NextCloud (fork of OwnCloud) instance on a Cubietruck attached to our router at home, etc. I am a huge privacy and F/LOSS/H advocate. I purchase hardware nowadays primarily based on how "open" the platform is, and/or their Linux driver support, etc. When I browse the internet, I block scripts and cross site requests, and only do so via VPN and/or TOR. You get the picture. So when I see the Google stuff, it makes me VERY VERY uncomfortable as I have gone to great lengths to avoid such. :(

**Comment by aumayr** [comment]
Fava does not have a direct dependency on anything from Google, see https://github.com/beancount/fava/search?q=google&unscoped_q=google

However, Beancount does (as you found out already). And Beancount is a dependency of Fava. Because of that, when you install Fava, all dependencies of it's dependencies will get installed, resulting in what you saw. 

So you can:
 
- Remove anything from Google _after_ you installed Fava. This may break Beancount, haven't tested that myself. 
- Open an issue like this on the Beancount Issue tracker here: https://bitbucket.org/blais/beancount/issues

(I guess if you really need it, @blais could make the Google dependencies optional for Beancount (as for example the Excel-related dependencies are for Fava), or you could submit a patch to Beancount for that yourself.)
