### ISSUE TITLE
With Beancount being a dependency of fava, do you end up with older version of Beancount?

### ISSUE THREAD

**Issue by TRSx80** [beancount/fava#792]
The Beancount [Installation Docs](https://docs.google.com/document/d/1FqyrTPwiHVLyncWTf3v5TcooCu9z5JRX8Nm41lVZi0U/edit#heading=h.hawoev1lvxb0) state:

> Installing Beancount using pip
> Note, however, that this will install the latest version that was pushed to the PyPI repository and not the very latest version available from source. Releases to PyPI are made sporadically but frequently enough not to be too far behind.

So I decided to clone the Beancount repository directly from Bitbucket using hg, in order to have the very latest version. I then followed the following instructions:

> Install Beancount from source using pip3
> You can then install all the dependencies and Beancount itself using pip:
`cd beancount`
`sudo pip3 install .`

...which, according to pip3 at that time gave me beancount-2.1.2-devel

Now when I installed fava, it says it installed beancount-2.1.2

I guess the reason I lodged this here, instead of at Beancount (or with Beancount Docs) is that I am wondering if it's a good idea to require beancount as a dependency of fava? I mean I'm sure there are a boatload of very obvious reasons (and perhaps it is necessary and/or there is no way around it?) but I suppose I wanted to make the point that it does break the ability to have the very latest version of Beancount.

Of course, I could be completely misunderstanding how pip3 works as well as I am just taking my first babby steps in learning Python. Would pip3 install an "older" version (2-1-2) or would it leave the "newer" 2-1-2-devel? I just did `$ pip3 freeze | grep beancount` which returned `beancount==2.1.2` so that's why I am guessing the former?

**Comment by aumayr** [comment]
Fava relies on/imports a lot of Beancount code, so not having it as a dependency is impossible. 

To do what you intended to do, you have to install in reverse order: Fava first, the latest version of Beancount second:

```
# pseudo-code
pip3 install fava
pip3 install ./beancount/ 
```

**Comment by xentac** [comment]
I think this is a bit more subtle. Something that we should probably address between beancount and fava.

https://www.python.org/dev/peps/pep-0440/#developmental-releases shows that devel versions are actually pre-releases. This means that 2.1.2-devel is development that will eventually become 2.1.2.

Looking at the beancount history, it looks like https://bitbucket.org/blais/beancount/commits/03bb037d4825e9e4279dc3508ff88fccec832eb8 incorrectly changed the beancount verison. It should have at least been changed to 2.1.3-devel.

I thought at first that -devel was being appended because we were building out of hg, but that doesn't seem to be the case.
