### ISSUE TITLE
Account filtering: prefer exact over fuzzy matches

### ISSUE THREAD

**Issue by TiraelSedai** [beancount/fava#969]
Here is similar issue:
https://github.com/beancount/fava/issues/698

Basically when I filter by, or create a new transaction, and enter "pets", my account "Expenses:Pets" is pretty far below because it's a fuzzy match. If I enter "Pets", it's first match as expected.

https://i.imgur.com/Vk0SQST.png

I would like to have "Expenses:Pets" to be the first result because it's the only account where "pets" characters go without a gap.

I don't think anyone wants account names to be case sensitive anyway.

**Comment by yagebu** [comment]
The matching is already case insensitive if you search by a lower case string. It's just that all the accounts in your example are fuzzy matched and they're sorted broadly by how much they're used.

**Comment by TiraelSedai** [comment]
Maybe I don't quite understand, but how exact match is fuzzy matched? By exact match I mean the exact sequence of characters.

**Comment by yagebu** [comment]
> Maybe I don't quite understand, but how exact match is fuzzy matched?

Fuzzy matching as implemented in Fava means the following: all the characters of the search string appear in the account name (and in the same order). So in particular, the exact string can be matched.

Of the accounts that are shown in your uploaded image all are fuzzy matched. The account Expenses:Pets is also fuzzy matched in a different sequence of characters than the exact match.

**Comment by TiraelSedai** [comment]
You are just playing with words, do you not understand my described intended behavior of the web app or do you say that the way it currently works is better?

In first case that should be an enhancement, in second case this issue should be closed with no further action and in no universe that was not a question.

**Comment by yagebu** [comment]
> You are just playing with words, do you not understand my described intended behavior of the web app or do you say that the way it currently works is better?

I was trying to explain how the fuzzy matching works to answer your question: "how exact match is fuzzy matched?" I guess I also don't quite understand your described intended behaviour: you first asked for the matching to be case insensitive, which it already is.

> P.S. Sorry if I'm sound upset, I just really hate when I got two answers with no actual answer whatsoever.

I answered two different questions of yours - one to state that the current matching is already case insensitive and then to explain the way the fuzzy matching works - since you asked. If you don't want me to answer your questions, then please spare the effort of writing them.

**Comment by yagebu** [comment]
> In first case that should be an enhancement, in second case this issue should be closed with no further action and in no universe that was not a question.

I didn't say that the current behaviour is perfect, I was just trying to describe how it works to explain how your implied proposed solution (making it case insensitive) is not possible since already implemented.

Of course it would be nice if the first result would always be the intended one. The ranking of the accounts exists for that purpose by suggesting the more often and recently used ones first. Ranking fuzzy matches by how well they match could improve this but that is a non-trivial problem IMHO.

**Comment by TiraelSedai** [comment]
I want the search to be case insensitive, and while it currently **CAN** output results that are in the different case, it most certainly does not output them at the top in case of exact match (as you said, it returns them in order of use frequency), however if you are putting the exact search phrase with a matching case, it would be on top (see Pets vs pets).

So in my mind, it should works like this:

1. We are looking up exact matches with something like `string.find(substring)` and place results on top
2. We are doing the fuzzy search and place results below

And what I wanted it to be is to search in the first case like `re.search(string, substring, re.IGNORECASE)`

While I may be wrong about it having two steps and rather everything falling under the "fuzzy search" one engine, my point is that the strings that have characters in the same order should be on top of those where the characters are in the same order _with a gaps_.

**Comment by yagebu** [comment]
Thanks for describing the behaviour you intend in detail :)

For my usual searches, it wouldn't much of an impact. The only negative one I can see is that it could move rather unused accounts to the top because they match a common short search string. Not sure if that would be annoying for others. Using the ranks (as computed by fava/util/ranking.py) of accounts and increasing that for exact matches could solve that - but could also be overkill ;)

To have the exact matches be consistent with the fuzzy ones, I think we should keep the current "smart case" behaviour (only case insensitive if the search string is all lowercase). 

> While I may be wrong about it having two steps and rather everything falling under the "fuzzy search" one engine, my point is that the strings that have characters in the same order should be on top of those where the characters are in the same order with a gaps.

I agree - your suggestion might be a simple enhancement without having to use/write a full-blown ranked fuzzy matcher (and having to merge that with the existing ranking)

**Comment by yagebu** [comment]
@TiraelSedai: are you interested in providing a PR with this enhancement?

**Comment by TiraelSedai** [comment]
I'll take a look if I can pull my weight but it's been a while since I've coded in Python, don't expect anything from me at least in fortnight.

**Comment by yagebu** [comment]
This part completely happens in the frontend, which is written in Typescript (so basically Javascript) - grepping for the fuzzymatch and fuzzywrap functions should point you to the places where this would need to be implemented.
