### ISSUE TITLE
Document not found if file names contain diacritics

### ISSUE THREAD

**Issue by jerome-tgl** [beancount/fava#983]
Fava 1.11 on Mac with Firefox 69.0.2 returns "not found" errors for every document that contains a diacritic, e.g
```
2019-10-11 * "ACME Inc." "Bank transfer"
  document: "2019-10-11  Relevé de situation.pdf"
  Asset:BankAccount       1000.00 EUR
  Revenue:Salary            -1000.00 EUR
```

I'm using `fava.plugins.tag_discovered_documents` and `fava.plugins.link_documents`.
 Problem does not occur on Linux though.

**Comment by yagebu** [comment]
I guess this is due to unicode normalisation. There are two equivalent ways to express the `é`: either as a single character `LATIN SMALL LETTER E WITH ACUTE` or as a combination of `LATIN SMALL LETTER E` and `COMBINING ACUTE ACCENT` see [here](http://www.fileformat.info/info/unicode/char/e9/index.html)

HFS+ at the file system level and APFS when used from Apple's higher level APIs (and in particular from probably any GUI application) use Normalization Form Canonical Decomposition (NFD) and uses the latter decomposed form. However, the character you entered on your keyboard into your Beancount file is probably of the first form as a single character. So when Fava tries to match the filename, it doesn't find it, as it has a different string of bytes as a filename. I'm not sure if this is actually a problem on HFS+, as it should do the normalisation at the lowest level. Which file system are you using?

I'm not sure if we should somehow handle this case from Fava. With unicode, there's often different strings that might be visually identical. On APFS, you could actually have two files with the "same" filename, one using the composed and one using the decomposed form (see https://eclecticlight.co/2017/04/06/apfs-is-currently-unusable-with-most-non-english-languages/). Which should we choose in this case? So IMHO this is a macOS issue - it's now doing file name normalisation in an inconsistent way.

**Comment by yagebu** [comment]
If you copy-paste the file name from Finder to your Beancount file, Fava should recognize the then matching filenames.
